create table category (ref integer not null auto_increment, img varchar(255), name varchar(255), primary key (ref)) engine=MyISAM;
create table content (ref integer not null auto_increment, ingredient_quantity double precision not null, ingredient_ref integer, recipe_ref integer, primary key (ref)) engine=MyISAM;
create table favorite (ref integer not null auto_increment, date datetime, recipe_ref integer, user_ref integer, primary key (ref)) engine=MyISAM;
create table image (ref integer not null auto_increment, url varchar(255), recipe_ref integer, primary key (ref)) engine=MyISAM;
create table ingredient (ref integer not null auto_increment, img varchar(255), name varchar(255), price float not null, unit varchar(255), primary key (ref)) engine=MyISAM;
create table reaction (ref integer not null auto_increment, recipe_ref integer, type_react_ref integer, user_ref integer, primary key (ref)) engine=MyISAM;
create table recipe (ref integer not null auto_increment, date datetime, description varchar(255), name varchar(255), time double precision not null, video varchar(255), category_ref integer, user_ref integer, primary key (ref)) engine=MyISAM;
create table type_react (ref integer not null auto_increment, img varchar(255), label varchar(255), primary key (ref)) engine=MyISAM;
create table user (ref integer not null auto_increment, age integer not null, description varchar(255), email varchar(255), name varchar(255), password varchar(255), photo varchar(255), primary key (ref)) engine=MyISAM;
alter table content add constraint FKcsqf5o8um0ydw3theva24aue2 foreign key (ingredient_ref) references ingredient (ref);
alter table content add constraint FKiwj8wetud4pbm3t64co80ve9u foreign key (recipe_ref) references recipe (ref);
alter table favorite add constraint FKbmyeopyjnab5a89ydj99ufa0i foreign key (recipe_ref) references recipe (ref);
alter table favorite add constraint FK4k8lfdvxvfd401nhmqy44skyg foreign key (user_ref) references user (ref);
alter table image add constraint FK3jmx4iwdugswis2155x2rkrgc foreign key (recipe_ref) references recipe (ref);
alter table reaction add constraint FK5sm1xf40dfo9b99aq27ythof3 foreign key (recipe_ref) references recipe (ref);
alter table reaction add constraint FKaeyoy9mtketb9per3hk1daumy foreign key (type_react_ref) references type_react (ref);
alter table reaction add constraint FK7nd4rrqf52qkjf1dly21eyst9 foreign key (user_ref) references user (ref);
alter table recipe add constraint FK9yjrk3enoqkdw47t68jtukxh7 foreign key (category_ref) references category (ref);
alter table recipe add constraint FK3jaoij4aio8xuhk6bkihamfc0 foreign key (user_ref) references user (ref);
